version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps): update npm dependencies"
    open-pull-requests-limit: 20