name: Publish Package to npmjs
on:
  release:
    types: [published]

jobs:
  build:
    name: Publish Package to npmjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Node.js version
        id: node_version
        run: echo node_version=$(cat .tool-versions | grep node | cut -d' ' -f2) >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node_version.outputs.node_version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to npmjs
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
